//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AgendaOnline.com.somee.pogramaweb2023 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgendaOnlineWSSoap", Namespace="http://tempuri.org/")]
    public partial class AgendaOnlineWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarGruposOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContactosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearGrupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearContactoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgendaOnlineWS() {
            this.Url = "http://pogramaweb2023.somee.com/AgendaOline/AgendaOnlineWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event LogueoCompletedEventHandler LogueoCompleted;
        
        /// <remarks/>
        public event ListarGruposCompletedEventHandler ListarGruposCompleted;
        
        /// <remarks/>
        public event ListarContactosCompletedEventHandler ListarContactosCompleted;
        
        /// <remarks/>
        public event CrearGrupoCompletedEventHandler CrearGrupoCompleted;
        
        /// <remarks/>
        public event CrearContactoCompletedEventHandler CrearContactoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateUser(string Nombre, string Apellido, string Email, string Telf, string Password) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        Nombre,
                        Apellido,
                        Email,
                        Telf,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(string Nombre, string Apellido, string Email, string Telf, string Password) {
            this.CreateUserAsync(Nombre, Apellido, Email, Telf, Password, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(string Nombre, string Apellido, string Email, string Telf, string Password, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        Nombre,
                        Apellido,
                        Email,
                        Telf,
                        Password}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logueo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Logueo(string Email, string password) {
            object[] results = this.Invoke("Logueo", new object[] {
                        Email,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoAsync(string Email, string password) {
            this.LogueoAsync(Email, password, null);
        }
        
        /// <remarks/>
        public void LogueoAsync(string Email, string password, object userState) {
            if ((this.LogueoOperationCompleted == null)) {
                this.LogueoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoOperationCompleted);
            }
            this.InvokeAsync("Logueo", new object[] {
                        Email,
                        password}, this.LogueoOperationCompleted, userState);
        }
        
        private void OnLogueoOperationCompleted(object arg) {
            if ((this.LogueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoCompleted(this, new LogueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarGrupos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GrupoWS[] ListarGrupos(string Email, string Password) {
            object[] results = this.Invoke("ListarGrupos", new object[] {
                        Email,
                        Password});
            return ((GrupoWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarGruposAsync(string Email, string Password) {
            this.ListarGruposAsync(Email, Password, null);
        }
        
        /// <remarks/>
        public void ListarGruposAsync(string Email, string Password, object userState) {
            if ((this.ListarGruposOperationCompleted == null)) {
                this.ListarGruposOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarGruposOperationCompleted);
            }
            this.InvokeAsync("ListarGrupos", new object[] {
                        Email,
                        Password}, this.ListarGruposOperationCompleted, userState);
        }
        
        private void OnListarGruposOperationCompleted(object arg) {
            if ((this.ListarGruposCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarGruposCompleted(this, new ListarGruposCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarContactos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContactoWS[] ListarContactos(string Email, string Password, int IdGroup) {
            object[] results = this.Invoke("ListarContactos", new object[] {
                        Email,
                        Password,
                        IdGroup});
            return ((ContactoWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContactosAsync(string Email, string Password, int IdGroup) {
            this.ListarContactosAsync(Email, Password, IdGroup, null);
        }
        
        /// <remarks/>
        public void ListarContactosAsync(string Email, string Password, int IdGroup, object userState) {
            if ((this.ListarContactosOperationCompleted == null)) {
                this.ListarContactosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContactosOperationCompleted);
            }
            this.InvokeAsync("ListarContactos", new object[] {
                        Email,
                        Password,
                        IdGroup}, this.ListarContactosOperationCompleted, userState);
        }
        
        private void OnListarContactosOperationCompleted(object arg) {
            if ((this.ListarContactosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContactosCompleted(this, new ListarContactosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearGrupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CrearGrupo(string Email, string Password, string NombreGrupo, string Color) {
            object[] results = this.Invoke("CrearGrupo", new object[] {
                        Email,
                        Password,
                        NombreGrupo,
                        Color});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearGrupoAsync(string Email, string Password, string NombreGrupo, string Color) {
            this.CrearGrupoAsync(Email, Password, NombreGrupo, Color, null);
        }
        
        /// <remarks/>
        public void CrearGrupoAsync(string Email, string Password, string NombreGrupo, string Color, object userState) {
            if ((this.CrearGrupoOperationCompleted == null)) {
                this.CrearGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearGrupoOperationCompleted);
            }
            this.InvokeAsync("CrearGrupo", new object[] {
                        Email,
                        Password,
                        NombreGrupo,
                        Color}, this.CrearGrupoOperationCompleted, userState);
        }
        
        private void OnCrearGrupoOperationCompleted(object arg) {
            if ((this.CrearGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearGrupoCompleted(this, new CrearGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CrearContacto(string Email, string Password, int IdGrupo, ContactoWS C) {
            object[] results = this.Invoke("CrearContacto", new object[] {
                        Email,
                        Password,
                        IdGrupo,
                        C});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearContactoAsync(string Email, string Password, int IdGrupo, ContactoWS C) {
            this.CrearContactoAsync(Email, Password, IdGrupo, C, null);
        }
        
        /// <remarks/>
        public void CrearContactoAsync(string Email, string Password, int IdGrupo, ContactoWS C, object userState) {
            if ((this.CrearContactoOperationCompleted == null)) {
                this.CrearContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearContactoOperationCompleted);
            }
            this.InvokeAsync("CrearContacto", new object[] {
                        Email,
                        Password,
                        IdGrupo,
                        C}, this.CrearContactoOperationCompleted, userState);
        }
        
        private void OnCrearContactoOperationCompleted(object arg) {
            if ((this.CrearContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearContactoCompleted(this, new CrearContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GrupoWS {
        
        private int idField;
        
        private string nombreField;
        
        private string colorField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactoWS {
        
        private int idField;
        
        private string nombreField;
        
        private string apellidosField;
        
        private string emailField;
        
        private string telfField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telf {
            get {
                return this.telfField;
            }
            set {
                this.telfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogueoCompletedEventHandler(object sender, LogueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarGruposCompletedEventHandler(object sender, ListarGruposCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarGruposCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarGruposCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GrupoWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GrupoWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarContactosCompletedEventHandler(object sender, ListarContactosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContactosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContactosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactoWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactoWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearGrupoCompletedEventHandler(object sender, CrearGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearContactoCompletedEventHandler(object sender, CrearContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591